config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'

  get 'home/show'

  root 'home#index' 

  resources :adverts

end

app/models/advert.rb
class Advert < ApplicationRecord
  has_many :advert_categories
  has_many :categories, through: :advert_categories
  belongs_to :user

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  validates :title, presence: true
  validates :title, length: { maximum: 80 }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/advert_category.rb
class AdvertCategory < ApplicationRecord
  belongs_to :categories
  belongs_to :adverts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include ActsAsTree
  extend ActsAsTree::TreeWalker
  extend ActsAsTree::TreeView

  has_many :advert_categories
  has_many :adverts, through: :advert_categories

  acts_as_tree :order => "name"

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :adverts
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  def index
    @adverts = current_user.adverts.all
  end

  def show
    @advert = current_user.adverts.find(params[:id])
  end

  def new
    @advert = current_user.adverts.new
    @advert_cat = Category.where(parent_id: 2)
  end

  def create
    @advert = current_user.adverts.new(strong_params)
    if @advert.save
      flash[:notice] = "Dodano nowe ogłoszenie"
      redirect_to adverts_path
    else
      flash[:error] = "Nie udało się dodać ogłoszenia"
      render :new
    end
  end

  def edit
    @advert = current_user.adverts.find(params[:id])
  end

  def update
    @advert = current_user.adverts.find(params[:id])
    if @advert.update(strong_params)
      flash[:notice] = "Ogłoszenie zostało zaktualizowane"
      redirect_to adverts_path
    else
      flash[:error] = "Nie udało się zaktualizować ogłoszenia"
      render :edit
    end
  end

  def destroy
    advert = current_user.adverts.find(params[:id])
    advert.destroy
    flash[:notice] = "Usunięto ogłoszenie: #{advert.title}"
    redirect_to adverts_path
  end

private
  def strong_params
    params.require(:advert).permit(:title, :description, :price)
  end

  def ancestry_options(items, &block)
    return ancestry_options(items){ |i| "#{'-' * i.depth} #{i.name}" } unless block_given?

    result = []
    items.map do |item, sub_items|
      result << [yield(item), item.id]
      #this is a recursive call:
      result += ancestry_options(sub_items, &block)
    end
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @adverts = Advert.all
  end

  def show
    @advert = Advert.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adverts/_form.html.erb
<%= form_for(advert) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :price %>
  <%= f.number_field(:price, step: 0.01) %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :category %>
  <%= f.select(:category) do %>
    

  <br />

  <%= f.submit "Zapisz" %>

<% end %>

app/views/adverts/edit.html.erb
<%= flash[:error] if flash[:error] %>
<h2>Edytuj ogłoszenie</h2>
<%= render partial: 'form', locals: { advert: @advert } %>

app/views/adverts/index.html.erb
<%= flash[:notice] if flash[:notice] %>
<h1>Moje ogłoszenia</h1>
<h3><%= link_to "Dodaj nowe ogłoszenie", new_advert_path %></h3>
<% @adverts.each do |ad| %>
  <div class="advert">
    <h2><%= link_to "#{ad.title}", advert_path(ad.id) %></h2>
    <p><%= ad.price %></p>
  </div>
<% end %>

app/views/adverts/new.html.erb
<%= flash[:error] if flash[:error] %>
<h2>Nowe ogłoszenie</h2>
<%= form_for(@advert) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :price %>
  <%= f.number_field(:price, step: 0.01) %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <% parent_category = @advert_cat %>
  <% unless Category.find_by(parent_id: parent_category.id) == nil %>
    <% categ_to_select = Category.where(parent_id: parent_category.id) %>
    <% tab = [] %>
    <% categ_to_select.each do |cat| %>
      <% tab << [cat.name, cat.id] %>
    <% end %>
    <%= f.select(:category) do %>
      <% tab.each do |c| %>
        <%= content_tag(:option, c.first, value: c.last) %>
      <% end %>
    <% end %>  
  <% end %>

  <%= f.submit "Zapisz" %>
<% end %>

app/views/adverts/show.html.erb
<%= flash[:notice] if flash[:notice] %>
<div>
  <h2><%= @advert.title %></h2>
  <div><%= link_to 'Edytuj', edit_advert_path(@advert.id) %> | <%= link_to 'Usuń', advert_path(@advert.id), method: :delete, data: { confirm: "Na pewno usunąć?" } %></div>
  <p><%= @advert.price %></p>
  <div><%= @advert.description %></div>
</div>

app/views/home/index.html.erb
<%= flash[:notice] if flash[:notice] %>
<h1>Nowe ogłoszenia</h1>
<%= @adverts.each do |ad| %>
  <div class='advert'>
    <h3><%= link_to "#{ad.title}", advert_path(ad.id) %></h3>
    <p><%= ad.price %></p>
  </div>
<% end %>
<h3><%= link_to "Dodaj ogłoszenie", new_advert_path %></h3>

app/views/home/new.html.erb
<%= flash[:error] if flash[:error] %>

<%= form_for @advert do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :price %>
  <%= f.number_field(:price, step: 0.01) %>

  <%= f.label :description %>
  <%= f.text_area(:description, size: "24x6") %>

  <br />

  <%= f.submit "Dodaj ogłoszenie" %>

<% end %>

app/views/home/show.html.erb
<div class="advert">
  <h1 class="title"><%= @advert.title %></h1>
  <h3 class="price"><%= @advert.price %></h3>
  <div class="description"><%= @advert.description %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdvertApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% if user_signed_in? %>
      Zalogowano jako <strong><%= current_user.email %></strong>.
      <%= link_to "Moje ogłoszenia", adverts_path, :class => 'navabar-link' %> | <%= link_to "Strona główna", home_index_path %> | <%= link_to 'Edytuj profil', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Wyloguj się",destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
    <% else %>
      <%= link_to "Załóż konto", new_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Zaloguj się",new_user_session_path, :class => 'navbar-link' %>
    <% end %>
    <%= yield %>
  </body>
</html>